CREATE TABLE table_001
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_002
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_003
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_004
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_005
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_006
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_007
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_008
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_009
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_010
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_011
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_012
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_013
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_014
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_015
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_016
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_017
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_018
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_019
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_020
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_021
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_022
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_023
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_024
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_025
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_026
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_027
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_028
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_029
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_030
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_031
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_032
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_033
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_034
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_035
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_036
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_037
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_038
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_039
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_040
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_041
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_042
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_043
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_044
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_045
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_046
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_047
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_048
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_049
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_050
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_051
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_052
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_053
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_054
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_055
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_056
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_057
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_058
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_059
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_060
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_061
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_062
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_063
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_064
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_065
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_066
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_067
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_068
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_069
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_070
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_071
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_072
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_073
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_074
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_075
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_076
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_077
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_078
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_079
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_080
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_081
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_082
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_083
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_084
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_085
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_086
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_087
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_088
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_089
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_090
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_091
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_092
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_093
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_094
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_095
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_096
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_097
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_098
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_099
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE table_100
(
    id INT NOT NULL,
    col1 VARCHAR(64) NOT NULL,
    col2 VARCHAR(64) NOT NULL,
    col3 VARCHAR(64) NOT NULL,
    col4 VARCHAR(64) NOT NULL,
    col5 VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
);
